### ISSUE TITLE
Invalid number

### ISSUE THREAD

**Issue by osama-raddad** [sinch/android-app-calling-contact-book#1]
i have tried to use your app but i have problem in the verification i have this exception : 

com.sinch.verification.ServiceErrorException: Sinch backend request failed with code: 40003 message: Invalid number. 

in the InitiationFailed part , i am entering the number in the  E.164 number formatting

**Comment by slavasav** [comment]
Hi! Could you send the number you are using to support@sinch.com?

**Comment by spacedsweden** [comment]
HI,

You need to enter the number e164 format (international format)
